DROP TABLE IF EXISTS events;
CREATE TABLE events (
	id INT AUTO_INCREMENT NOT NULL,
	name TEXT NOT NULL DEFAULT "",
	descr TEXT NOT NULL DEFAULT "",
	PRIMARY KEY (id)
) DEFAULT CHARSET=utf8;
ALTER TABLE events AUTO_INCREMENT=1000;

DROP TABLE IF EXISTS parties;
CREATE TABLE parties (
	id INT AUTO_INCREMENT NOT NULL,
	name TEXT NOT NULL DEFAULT "",
	comment TEXT NOT NULL DEFAULT "",
	PRIMARY KEY (id)
) DEFAULT CHARSET=utf8;
ALTER TABLE parties AUTO_INCREMENT=2000;

DROP TABLE IF EXISTS guests;
CREATE TABLE guests (
	id INT AUTO_INCREMENT NOT NULL,
	party_id INT NOT NULL,
	name TEXT NOT NULL DEFAULT "",
	is_plus_one BOOL NOT NULL DEFAULT 0,
	PRIMARY KEY (id)
) DEFAULT CHARSET=utf8;
ALTER TABLE guests AUTO_INCREMENT=3000;

DROP TABLE IF EXISTS invitations;
CREATE TABLE invitations (
	party_id INT NOT NULL,
	event_id INT NOT NULL,
	PRIMARY KEY (party_id, event_id)
) DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS responses;
CREATE TABLE responses (
	guest_id INT NOT NULL,
	event_id INT NOT NULL,
	response BOOL NOT NULL,
	PRIMARY KEY (guest_id, event_id)
) DEFAULT CHARSET=utf8;
