DROP TABLE IF EXISTS parties;
CREATE TABLE parties (
	id INT AUTO_INCREMENT NOT NULL,
	name TEXT NOT NULL DEFAULT "",
	comment TEXT NOT NULL DEFAULT "",
	rehearsal_invited BOOL NOT NULL DEFAULT 0,
	PRIMARY KEY (id)
) DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS guests;
CREATE TABLE guests (
	id INT AUTO_INCREMENT NOT NULL,
	party_id INT NOT NULL,
	name TEXT NOT NULL DEFAULT "",
	response BOOL DEFAULT NULL,
	rehearsal_response BOOL DEFAULT NULL,
	is_plus_one BOOL NOT NULL DEFAULT 0,
	PRIMARY KEY (id)
) DEFAULT CHARSET=utf8;
